apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "example.fullname" . }}
  labels:
    app: {{ template "example.name" . }}
    chart: {{ template "example.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - "example.com"
  gateways:
  - {{ template "example.fullname" . }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ template "example.fullname" . }}
